# Generated by Django 5.2 on 2025-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_annonce_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
